# 1. Firstly, in root folder just create an image 
# > docker build -t asatklichov/springtech .
# 2. in docker folder just use docker-compose file to run the app
# > docker-compose build
# > docker-compose up


version: '2'
services:

  springtech:
    #build:
    #  context: .
    #  dockerfile: ../Dockerfile
    image: asatklichov/springtech
    build: ./
    #environment:
    #  - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/springtech
    ports:
      - "9999:9999"
    depends_on:
      - springtech-postgresql
    #networks:
    #  - my_isolated_net2
      
  springtech-postgresql:
    image: postgres:11.4-alpine
    # volumes:
    # - ~/volumes/valo/postgresql/:/var/lib/postgresql/data/
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=springtech
    ports:
     - "5435:5432"
    #volumes:
    # - sample_db:/var/lib/postgresql/data
    #networks:
    # - my_isolated_net2
    
  #volumes:
  # sample_db:

  #networks:
  # my_isolated_net2:
  #  driver: bridge        
  