create table if not exists spitter (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(25) not null,
  password varchar(25) not null,
  fullName varchar(100) not null,
  email varchar(50) not null,
  updateByEmail boolean not null
);

create table if not exists spittle (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  spitter integer not null,
  message varchar(2000) not null,
  postedTime date not null,
  foreign key (spitter) references spitter(id)
);